#pragma libcall BBXBase FileSize 1E 801
#pragma libcall BBXBase ObtainMessage 24 198004
#pragma libcall BBXBase ReleaseMessage 2A 1002
#pragma libcall BBXBase CreateMessage 30 09803
#pragma libcall BBXBase DeleteMessage 36 1002
#pragma libcall BBXBase GetNodeState 3C 1002
#pragma libcall BBXBase GetLowMessage 42 0
#pragma libcall BBXBase GetHighMessage 48 0
#pragma libcall BBXBase GetNumCallers 4E 0
#pragma libcall BBXBase SetNumCallers 54 001
#pragma libcall BBXBase AddNode 5A 801
#pragma libcall BBXBase RemoveNode 60 801
#pragma libcall BBXBase FlushData 66 0
#pragma libcall BBXBase GetMessageHeader 6C 18003
#pragma libcall BBXBase UpdateMessageHeader 72 0802
#pragma libcall BBXBase ObtainItem 78 801
#pragma libcall BBXBase AttemptItem 7E 801
#pragma libcall BBXBase ReleaseItem 84 801
#pragma libcall BBXBase GetNodeAddress 8A 801
#pragma libcall BBXBase SendNodeMessage 90 9802
#pragma libcall BBXBase GetMessageText 96 09803
#pragma libcall BBXBase GetUserVariable 9C 0A9804
#pragma libcall BBXBase SetUserVariable A2 A9803
#pragma libcall BBXBase GetActiveMessages A8 0
#pragma libcall BBXBase LockBBXLibrary AE 0
#pragma libcall BBXBase UnlockBBXLibrary B4 0
#pragma libcall BBXBase FreeLibraryResources BA 0
#pragma libcall BBXBase ReopenLibraryResources C0 0
